/* Code generated by cmd/cgo; DO NOT EDIT. */

#include <stdlib.h>
#include "_cgo_export.h"

#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wpragmas"
#pragma GCC diagnostic ignored "-Waddress-of-packed-member"
#pragma GCC diagnostic ignored "-Wunknown-warning-option"
#pragma GCC diagnostic ignored "-Wunaligned-access"
extern void crosscall2(void (*fn)(void *), void *, int, size_t);
extern size_t _cgo_wait_runtime_init_done(void);
extern void _cgo_release_context(size_t);

extern char* _cgo_topofstack(void);
#define CGO_NO_SANITIZE_THREAD
#define _cgo_tsan_acquire()
#define _cgo_tsan_release()


#define _cgo_msan_write(addr, sz)

extern void _cgoexp_c6cfbd27125d_AckedIndexC(void *);

CGO_NO_SANITIZE_THREAD
void AckedIndexC(void* l, uint64_t id, uint64_t* idx, void* ok)
{
	size_t _cgo_ctxt = _cgo_wait_runtime_init_done();
	typedef struct {
		void* p0;
		uint64_t p1;
		uint64_t* p2;
		void* p3;
	} __attribute__((__packed__)) _cgo_argtype;
	static _cgo_argtype _cgo_zero;
	_cgo_argtype _cgo_a = _cgo_zero;
	_cgo_a.p0 = l;
	_cgo_a.p1 = id;
	_cgo_a.p2 = idx;
	_cgo_a.p3 = ok;
	_cgo_tsan_release();
	crosscall2(_cgoexp_c6cfbd27125d_AckedIndexC, &_cgo_a, 32, _cgo_ctxt);
	_cgo_tsan_acquire();
	_cgo_release_context(_cgo_ctxt);
}
